export const OPEN_PLATFORM_IN_TAB = 'OPEN_PLATFORM_IN_TAB';
export const CLOSE_PLATFORM_IN_TAB = 'CLOSE_PLATFORM_IN_TAB';
export const BLUR_TAB = 'BLUR_TAB';
export const FOCUS_TAB = 'FOCUS_TAB';
export const FOCUS_ON_REACTION_INPUT = 'FOCUS_ON_REACTION_INPUT';
export const BLUR_ON_REACTION_INPUT = 'BLUR_ON_REACTION_INPUT';
// export const POINTER_ACTIVITY_RECORD = 'POINTER_ACTIVITY_RECORD';
export const BROWSE_VIEW = 'BROWSE_VIEW';
export const CHAT_ACTIVITY_RECORD = 'CHAT_ACTIVITY_RECORD';
// export const IS_PLAYING_ACTIVITY_RECORD = 'IS_PLAYING_ACTIVITY_RECORD';
export const LIVE_USER_ACTIVITY_RECORD = 'LIVE_USER_ACTIVITY_RECORD';

export const EVENT_TYPES = [
  OPEN_PLATFORM_IN_TAB,
  CLOSE_PLATFORM_IN_TAB,
  BLUR_TAB,
  FOCUS_TAB,
  FOCUS_ON_REACTION_INPUT,
  BLUR_ON_REACTION_INPUT,
  // POINTER_ACTIVITY_RECORD,
  BROWSE_VIEW,
  CHAT_ACTIVITY_RECORD,
  // IS_PLAYING_ACTIVITY_RECORD,
  LIVE_USER_ACTIVITY_RECORD,
]

/**
 * SETTINGS ACTIONS
 */
export const GET_SETTINGS = 'GET_SETTINGS';
export const SET_SETTING = 'SET_SETTING';

/**
 * ANNOTATIONS ACTIONS
 */
export const GET_ANNOTATIONS = 'GET_ANNOTATIONS';
export const GET_ANNOTATIONS_COLLECTION = 'GET_ANNOTATIONS_COLLECTION';
export const UPDATE_ANNOTATION_COLLECTION = 'UPDATE_ANNOTATION_COLLECTION';
export const CREATE_ANNOTATION = 'CREATE_ANNOTATION';
export const UPDATE_ANNOTATION = 'UPDATE_ANNOTATION';
export const DELETE_ANNOTATION = 'DELETE_ANNOTATION';

/**
 * Generic processes control actions
 */
export const ACTION_END = 'ACTION_END';
export const ACTION_PROGRESS = 'ACTION_PROGRESS';

/**
 * Dev actions
 */
export const DUPLICATE_DAY_DATA = 'DUPLICATE_DAY_DATA';
export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';
export const SERIALIZE_ALL_DATA = 'SERIALIZE_ALL_DATA';
export const APPEND_ACTIVITY_EVENTS = 'APPEND_ACTIVITY_EVENTS';
export const PREPEND_ACTIVITY_EVENTS = 'PREPEND_ACTIVITY_EVENTS';
export const REPLACE_ACTIVITY_EVENTS = 'REPLACE_ACTIVITY_EVENTS';

export const GET_BINNED_ACTIVITY_OUTLINE = 'GET_BINNED_ACTIVITY_OUTLINE';
export const GET_ACTIVITY_EVENTS = 'GET_ACTIVITY_EVENTS';
export const GET_CHANNELS = 'GET_CHANNELS';

export const PLATFORMS = ['twitch', 'youtube']

export const DEFAULT_SETTINGS = {
  handles: [],
  recordOnPlatforms: PLATFORMS,
  liveRecordingInterval: 10000,
  recordActivity: true,
  recordTabs: true,
  recordMouse: true,
  recordChat: true
}

export const DEFAULT_ANNOTATIONS = {
  creators: {},
  tags: {},
  expressions: {}
} 

export const PLATFORMS_COLORS = {
  twitch: '#aa43ff',
  youtube: '#ff0001'
}